/**
 * Built-in question bank for Change of Subject of Formula.
 * Imported by the engine as a fallback when no questions are supplied
 * in the mission payload — lets the engine run standalone in dev/testing.
 * For production, supply questions via mission payload in the DB.
 */

import type { CosQuestion } from "./changeOfSubject.config";

const t = (text: string, b = false) => ({ type: "term" as const, t: text, b });
const f = (n: string, d: string, b = false) => ({ type: "frac" as const, n, d, b });
const s = (inner: unknown[], b = false) => ({ type: "sqrt" as const, inner, b });
const o = (text: string) => ({ type: "op" as const, t: text });

export const BUILTIN_QUESTIONS: CosQuestion[] = [
  // Q1 — v = u + at, find t
  {
    qLabel: "Make t the subject",
    formula: "v = u + at",
    finalAnswer: "t = (v − u) / a",
    steps: [
      {
        leftToks: [t("u"), o("+"), t("at", true)],
        rightToks: [t("v")],
        mascot: "We want <strong>t</strong> alone. <strong>u</strong> is on the same side — subtract u from both sides.",
        instPrac: "u is blocking at — subtract u from both sides.",
        instChall: "Make t the subject  ·  v = u + at",
        hint: "The opposite of + u is − u.",
        tileOk: "− u",
        tilesNo: ["+ u", "÷ u"],
        whyNot: {
          "+ u": "Adding u makes it larger on that side — moves further away from being removed.",
          "÷ u": "Dividing by u doesn't cancel the u we need to remove.",
        },
        lqT: [t("u + at − u")],
        lAns: "at",
        lWrong: ["a+t", "u·t"],
        rqT: [t("v − u")],
        rAns: "v − u",
        rWrong: ["v+u", "v/u"],
        newLeft: [t("at")],
        newRight: [t("v − u")],
      },
      {
        leftToks: [t("at", true)],
        rightToks: [t("v − u")],
        mascot: "<strong>t</strong> is multiplied by a — divide both sides by a to isolate t.",
        instPrac: "t is multiplied by a — divide both sides by a.",
        instChall: "Make t the subject  ·  v = u + at",
        hint: "÷ a leaves t on its own.",
        tileOk: "÷ a",
        tilesNo: ["× a", "− a"],
        whyNot: {
          "× a": "Multiplying by a gives a²t — coefficient grows, not shrinks.",
          "− a": "Subtracting a doesn't remove the a that's multiplying t.",
        },
        lqT: [t("at ÷ a")],
        lAns: "t",
        lWrong: ["a/t", "at²"],
        rqT: [t("(v − u) ÷ a")],
        rAns: "(v−u)/a",
        rWrong: ["v−u+a", "a(v−u)"],
        newLeft: [t("t")],
        newRight: [f("v − u", "a")],
      },
    ],
  },

  // Q2 — P = 2(l + w), find l
  {
    qLabel: "Make l the subject",
    formula: "P = 2(l + w)",
    finalAnswer: "l = P/2 − w",
    steps: [
      {
        leftToks: [t("2(l + w)", true)],
        rightToks: [t("P")],
        mascot: "l is inside brackets being <strong>multiplied by 2</strong> — divide both sides by 2.",
        instPrac: "l is inside brackets × 2 — divide both sides by 2.",
        instChall: "Make l the subject  ·  P = 2(l + w)",
        hint: "÷ 2 removes the coefficient outside the bracket.",
        tileOk: "÷ 2",
        tilesNo: ["× 2", "− 2"],
        whyNot: {
          "× 2": "Multiplying by 2 doubles the coefficient — makes it worse.",
          "− 2": "Subtracting 2 doesn't remove the 2 multiplying the bracket.",
        },
        lqT: [t("2(l+w) ÷ 2")],
        lAns: "l + w",
        lWrong: ["2l+w", "l+2w"],
        rqT: [t("P ÷ 2")],
        rAns: "P/2",
        rWrong: ["2P", "P−2"],
        newLeft: [t("l + w")],
        newRight: [f("P", "2")],
      },
      {
        leftToks: [t("l"), o("+"), t("w", true)],
        rightToks: [f("P", "2")],
        mascot: "<strong>w</strong> is still next to l — subtract w from both sides.",
        instPrac: "w is next to l — subtract w from both sides.",
        instChall: "Make l the subject  ·  P = 2(l + w)",
        hint: "− w cancels the + w on the left.",
        tileOk: "− w",
        tilesNo: ["+ w", "× w"],
        whyNot: {
          "+ w": "Adding w makes w larger on l's side.",
          "× w": "Multiplying by w introduces w² unnecessarily.",
        },
        lqT: [t("l + w − w")],
        lAns: "l",
        lWrong: ["l+2w", "l−w"],
        rqT: [f("P", "2"), t("− w")],
        rAns: "P/2 − w",
        rWrong: ["P/2+w", "Pw/2"],
        newLeft: [t("l")],
        newRight: [f("P", "2"), o("−"), t("w")],
      },
    ],
  },

  // Q3 — A = πr², find r
  {
    qLabel: "Make r the subject",
    formula: "A = πr²",
    finalAnswer: "r = √(A/π)",
    steps: [
      {
        leftToks: [t("πr²", true)],
        rightToks: [t("A")],
        mascot: "r² is being <strong>multiplied by π</strong> — divide both sides by π.",
        instPrac: "r² is multiplied by π — divide both sides by π.",
        instChall: "Make r the subject  ·  A = πr²",
        hint: "÷ π removes the π coefficient.",
        tileOk: "÷ π",
        tilesNo: ["× π", "− π"],
        whyNot: {
          "× π": "Multiplying by π gives π²r² — makes things bigger.",
          "− π": "Subtracting π doesn't remove the π multiplying r².",
        },
        lqT: [t("πr² ÷ π")],
        lAns: "r²",
        lWrong: ["r", "πr"],
        rqT: [t("A ÷ π")],
        rAns: "A/π",
        rWrong: ["Aπ", "A−π"],
        newLeft: [t("r²")],
        newRight: [f("A", "π")],
      },
      {
        leftToks: [t("r²", true)],
        rightToks: [f("A", "π")],
        mascot: "r is <strong>squared</strong> — take the square root of both sides.",
        instPrac: "r is squared — √ both sides removes the ².",
        instChall: "Make r the subject  ·  A = πr²",
        hint: "√(r²) = r",
        tileOk: "√( )",
        tilesNo: ["( )²", "÷ 2"],
        whyNot: {
          "( )²": "Squaring again gives r⁴ — moves further from r alone.",
          "÷ 2": "Dividing by 2 doesn't remove the square on r.",
        },
        lqT: [t("√(r²)")],
        lAns: "r",
        lWrong: ["r²", "2r"],
        rqT: [t("√(A/π)")],
        rAns: "√(A/π)",
        rWrong: ["A/π", "√A÷√π"],
        newLeft: [t("r")],
        newRight: [s([f("A", "π")])],
      },
    ],
  },

  // Q4 — s = ut + ½at², find u
  {
    qLabel: "Make u the subject",
    formula: "s = ut + ½at²",
    finalAnswer: "u = (s − ½at²) / t",
    steps: [
      {
        leftToks: [t("ut", true), o("+"), t("½at²")],
        rightToks: [t("s")],
        mascot: "<strong>½at²</strong> is on the same side as ut — subtract it from both sides.",
        instPrac: "½at² is blocking — subtract it from both sides.",
        instChall: "Make u the subject  ·  s = ut + ½at²",
        hint: "Subtract ½at² to leave ut alone.",
        tileOk: "− ½at²",
        tilesNo: ["+ ½at²", "÷ t"],
        whyNot: {
          "+ ½at²": "Adding ½at² makes that term even bigger.",
          "÷ t": "Dividing by t now splits ½at² into ½at — messy.",
        },
        lqT: [t("ut + ½at² − ½at²")],
        lAns: "ut",
        lWrong: ["ut+at²", "u+½t²"],
        rqT: [t("s − ½at²")],
        rAns: "s − ½at²",
        rWrong: ["s+½at²", "s/½at²"],
        newLeft: [t("ut")],
        newRight: [t("s − ½at²")],
      },
      {
        leftToks: [t("ut", true)],
        rightToks: [t("s − ½at²")],
        mascot: "<strong>u</strong> is multiplied by t — divide both sides by t.",
        instPrac: "u is multiplied by t — divide both sides by t.",
        instChall: "Make u the subject  ·  s = ut + ½at²",
        hint: "÷ t leaves u on its own.",
        tileOk: "÷ t",
        tilesNo: ["× t", "− t"],
        whyNot: {
          "× t": "Multiplying by t gives ut² — adds another t.",
          "− t": "Subtracting t gives ut − t — t still multiplies u.",
        },
        lqT: [t("ut ÷ t")],
        lAns: "u",
        lWrong: ["ut²", "u/t"],
        rqT: [t("(s − ½at²) ÷ t")],
        rAns: "(s−½at²)/t",
        rWrong: ["t(s−½at²)", "s/t"],
        newLeft: [t("u")],
        newRight: [f("s − ½at²", "t")],
      },
    ],
  },

  // Q5 — T = 2π√(l/g), find l
  {
    qLabel: "Make l the subject",
    formula: "T = 2π√(l/g)",
    finalAnswer: "l = T²g / 4π²",
    steps: [
      {
        leftToks: [t("2π", true), s([f("l", "g")])],
        rightToks: [t("T")],
        mascot: "The square root is being <strong>multiplied by 2π</strong> — divide both sides by 2π.",
        instPrac: "√(l/g) is × 2π outside — divide both sides by 2π.",
        instChall: "Make l the subject  ·  T = 2π√(l/g)",
        hint: "÷ 2π isolates the square root.",
        tileOk: "÷ 2π",
        tilesNo: ["× 2π", "− 2π"],
        whyNot: {
          "× 2π": "Multiplying by 2π gives 4π²√(l/g) — coefficient grows.",
          "− 2π": "Subtracting 2π doesn't remove the 2π multiplying the root.",
        },
        lqT: [t("2π√(l/g) ÷ 2π")],
        lAns: "√(l/g)",
        lWrong: ["√(l/g)/2π", "2π√(l/g)"],
        rqT: [t("T ÷ 2π")],
        rAns: "T/2π",
        rWrong: ["2πT", "T−2π"],
        newLeft: [s([f("l", "g")])],
        newRight: [f("T", "2π")],
      },
      {
        leftToks: [s([f("l", "g")], true)],
        rightToks: [f("T", "2π")],
        mascot: "l is inside a square root — <strong>square both sides</strong> to remove it.",
        instPrac: "l is inside √ — square both sides to remove it.",
        instChall: "Make l the subject  ·  T = 2π√(l/g)",
        hint: "(√x)² = x",
        tileOk: "( )²",
        tilesNo: ["√( )", "÷ 2"],
        whyNot: {
          "√( )": "Another root gives ⁴√(l/g) — deeper, not simpler.",
          "÷ 2": "Dividing by 2 doesn't remove a square root.",
        },
        lqT: [t("(√(l/g))²")],
        lAns: "l/g",
        lWrong: ["l²/g", "√(l/g)"],
        rqT: [f("T", "2π"), t("²")],
        rAns: "T²/4π²",
        rWrong: ["T/4π²", "T²/2π"],
        newLeft: [f("l", "g")],
        newRight: [f("T²", "4π²")],
      },
      {
        leftToks: [f("l", "g", true)],
        rightToks: [f("T²", "4π²")],
        mascot: "l is being <strong>divided by g</strong> — multiply both sides by g.",
        instPrac: "l is divided by g — multiply both sides by g.",
        instChall: "Make l the subject  ·  T = 2π√(l/g)",
        hint: "× g cancels the /g under l.",
        tileOk: "× g",
        tilesNo: ["÷ g", "+ g"],
        whyNot: {
          "÷ g": "Dividing again gives l/g² — fraction gets deeper.",
          "+ g": "Adding g doesn't remove the division.",
        },
        lqT: [t("(l/g) × g")],
        lAns: "l",
        lWrong: ["l/g²", "lg"],
        rqT: [f("T²", "4π²"), t("× g")],
        rAns: "T²g/4π²",
        rWrong: ["T²/4π²g", "gT²/2π"],
        newLeft: [t("l")],
        newRight: [f("T²g", "4π²")],
      },
    ],
  },
];
