// FILE: src/engines/cross-subject/guided-lesson/GuidedLessonEngine.tsx
"use client";

/**
 * GuidedLessonEngine
 *
 * Renders a structured guided learning lesson from a lessonFlow array.
 * Each step is one of: COACH (text card), INTERACT (interaction component),
 * SUCCESS (completion screen).
 *
 * The lesson flow is generated by the CMS publish pipeline and stored
 * in mission.payload.lessonFlow.
 */

import React, { useState, lazy, Suspense } from "react";
import type { EngineRuntimeProps } from "@/engines/engine-types";

// Import MCQEngine for practice/challenge missions
import { MCQEngine } from "@/engines/cross-subject/mcq/MCQEngine";

// Lazy-load interaction components — same registry as CMS
const INTERACTION_COMPONENTS: Record<string, React.ComponentType<{ config: Record<string, unknown>; colour?: string }>> = {
  HeatSlider:           lazy(() => import("@/components/interactions/HeatSlider")),
  MatterSorter:         lazy(() => import("@/components/interactions/MatterSorter")),
  InfiniteZoomExplorer: lazy(() => import("@/components/interactions/InfiniteZoomExplorer")),
};

interface FlowStep {
  type: "COACH" | "INTERACT" | "SUCCESS";
  text?: string;
  cardIndex?: number;
  isKeyMoment?: boolean;
  component?: string;
  config?: Record<string, unknown>;
  objectives?: string[];
}

interface MissionPayload {
  type: string;
  lessonFlow?: FlowStep[];
  objectives?: string[];
  conceptName?: string;
}

interface SharedConfig {
  coach?: string;
  accentColour?: string;
  subject?: string;
  topicName?: string;
}

interface GuidedLessonConfig {
  shared: SharedConfig;
  mission: {
    payload: MissionPayload;
    title?: string;
    difficulty?: string;
  };
}

interface GuidedLessonOutcome {
  completed: boolean;
  stepsCompleted: number;
}

const SUBJECT_BG: Record<string, string> = {
  chemistry:   "linear-gradient(160deg, #0c2d48 0%, #0a1628 100%)",
  physics:     "linear-gradient(160deg, #1a0533 0%, #0d0820 100%)",
  mathematics: "linear-gradient(160deg, #062318 0%, #041810 100%)",
  biology:     "linear-gradient(160deg, #1a1000 0%, #0f0900 100%)",
};

export function GuidedLessonEngine({
  config,
  onComplete,
  menu,
}: EngineRuntimeProps<GuidedLessonConfig, GuidedLessonOutcome> & { menu?: React.ReactNode }) {
  const shared = (config.shared ?? {}) as SharedConfig;
  const payload = (config.mission?.payload ?? {}) as MissionPayload;

  // Route to MCQEngine for practice and challenge missions
  if (payload.type === "mcq") {
    return (
      <MCQEngine
        config={config as unknown as import("@/engines/cross-subject/mcq/MCQEngine").MCQConfig}
        onComplete={onComplete as unknown as (outcome: import("@/engines/cross-subject/mcq/MCQEngine").MCQOutcome) => void}
        menu={menu}
      />
    );
  }

  const lessonFlow = payload.lessonFlow ?? [];
  const objectives = payload.objectives ?? [];
  const coach = shared.coach ?? "Dr. Adaobi";
  const accentColour = shared.accentColour ?? "#0284c7";
  const [stepIdx, setStepIdx] = useState(0);
  const [interactionDone, setInteractionDone] = useState(false);

  const step = lessonFlow[stepIdx];
  const isLast = stepIdx === lessonFlow.length - 1;
  const isFirst = stepIdx === 0;

  const advance = () => {
    if (isLast) {
      onComplete({ completed: true, stepsCompleted: lessonFlow.length });
    } else {
      setStepIdx(s => s + 1);
      setInteractionDone(false);
    }
  };

  const colour = accentColour;
  const LiveComponent = step?.component ? INTERACTION_COMPONENTS[step.component] : null;

  return (
    <div style={{
      background: "#060d18",
      minHeight: "100vh",
      display: "flex",
      flexDirection: "column",
      position: "relative",
    }}>
      {/* Top row with menu */}
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "12px 16px 0" }}>
        <div style={{ display: "flex", gap: 4, alignItems: "center" }}>
          {lessonFlow.map((_, i) => (
            <div key={i} style={{
              width: i === stepIdx ? 16 : 5, height: 5, borderRadius: 3,
              background: i <= stepIdx ? colour : "rgba(255,255,255,0.12)",
              transition: "all 0.2s",
            }} />
          ))}
          <div style={{ marginLeft: 8, fontSize: "0.62rem", color: "rgba(255,255,255,0.3)" }}>
            {stepIdx + 1}/{lessonFlow.length}
          </div>
        </div>
        {menu && <div>{menu}</div>}
      </div>
      {/* Thin progress bar */}
      <div style={{ height: 2, background: "rgba(255,255,255,0.06)", marginTop: 8 }}>
        <div style={{
          height: "100%",
          width: `${((stepIdx + 1) / lessonFlow.length) * 100}%`,
          background: colour,
          transition: "width 0.3s",
        }} />
      </div>



      {/* Content */}
      <div style={{ flex: 1, padding: "16px 20px", overflowY: "auto" }}>

        {/* COACH step */}
        {step?.type === "COACH" && (
          <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
            <div style={{ display: "flex", gap: 12, alignItems: "center" }}>
              <div style={{
                width: 44, height: 44, borderRadius: "50%", flexShrink: 0,
                background: `${colour}20`, border: `2px solid ${colour}`,
                display: "flex", alignItems: "center", justifyContent: "center", fontSize: 22,
              }}>🧑‍🔬</div>
              <div>
                <div style={{ fontSize: "0.9rem", fontWeight: 800, color: "#fff" }}>{coach}</div>
                <div style={{ fontSize: "0.68rem", color: colour }}>
                  {step.isKeyMoment ? "Key insight" : "Your guide"}
                </div>
              </div>
            </div>

            <div style={{
              background: step.isKeyMoment ? `${colour}12` : "rgba(255,255,255,0.05)",
              borderRadius: 16, padding: 20,
              border: step.isKeyMoment ? `1px solid ${colour}35` : "1px solid rgba(255,255,255,0.08)",
              borderLeft: step.isKeyMoment ? `4px solid ${colour}` : undefined,
            }}>
              <div style={{ fontSize: "1rem", color: "rgba(255,255,255,0.9)", lineHeight: 1.7 }}>
                {step.text}
              </div>
            </div>
          </div>
        )}

        {/* INTERACT step */}
        {step?.type === "INTERACT" && (
          <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
            <div style={{ fontSize: "0.65rem", fontWeight: 800, color: colour, textTransform: "uppercase", letterSpacing: "0.1em" }}>
              Your turn
            </div>
            {LiveComponent ? (
              <Suspense fallback={
                <div style={{ padding: 40, textAlign: "center", color: "rgba(255,255,255,0.3)" }}>
                  Loading interaction…
                </div>
              }>
                <LiveComponent config={step.config ?? {}} colour={colour} />
              </Suspense>
            ) : (
              <div style={{ padding: 24, textAlign: "center", background: "rgba(255,255,255,0.04)", borderRadius: 12 }}>
                <div style={{ fontSize: "0.82rem", color: "rgba(255,255,255,0.3)" }}>
                  Interaction: {step.component ?? "unknown"}
                </div>
              </div>
            )}
            {!interactionDone && (
              <button onClick={() => setInteractionDone(true)} style={{
                padding: "10px", borderRadius: 10, border: "none",
                background: `${colour}20`, color: colour,
                fontSize: "0.82rem", fontWeight: 700, cursor: "pointer",
              }}>
                I&apos;ve explored this →
              </button>
            )}
          </div>
        )}

        {/* SUCCESS step */}
        {step?.type === "SUCCESS" && (
          <div style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: 20, paddingTop: 20, textAlign: "center" }}>
            <div style={{ fontSize: "3rem" }}>🎯</div>
            <div style={{ fontSize: "1.2rem", fontWeight: 800, color: "#fff" }}>Well done!</div>
            <div style={{
              background: "rgba(5,150,105,0.12)", borderRadius: 16, padding: 20,
              border: "1px solid rgba(5,150,105,0.25)", width: "100%",
            }}>
              <div style={{ fontSize: "0.95rem", color: "rgba(255,255,255,0.85)", lineHeight: 1.7, fontStyle: "italic" }}>
                &quot;{step.text}&quot;
              </div>
            </div>
            {(step.objectives ?? objectives).filter(Boolean).length > 0 && (
              <div style={{ width: "100%", textAlign: "left" }}>
                <div style={{ fontSize: "0.65rem", fontWeight: 700, color: "rgba(255,255,255,0.3)", textTransform: "uppercase", marginBottom: 10 }}>
                  What you learned
                </div>
                {(step.objectives ?? objectives).filter(Boolean).map((obj: string, i: number) => (
                  <div key={i} style={{ display: "flex", gap: 10, alignItems: "flex-start", marginBottom: 8 }}>
                    <div style={{ color: "#34d399", flexShrink: 0 }}>✓</div>
                    <div style={{ fontSize: "0.85rem", color: "rgba(255,255,255,0.7)", lineHeight: 1.5 }}>{obj}</div>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}
      </div>

      {/* Navigation */}
      <div style={{ padding: "12px 20px", borderTop: "1px solid rgba(255,255,255,0.06)", display: "flex", gap: 10 }}>
        {!isFirst && (
          <button onClick={() => setStepIdx(s => Math.max(0, s - 1))} style={{
            padding: "12px 20px", borderRadius: 12,
            border: "1px solid rgba(255,255,255,0.12)", background: "transparent",
            color: "rgba(255,255,255,0.5)", fontSize: "0.85rem", cursor: "pointer",
          }}>← Back</button>
        )}
        <button
          onClick={advance}
          disabled={step?.type === "INTERACT" && !interactionDone}
          style={{
            flex: 1, padding: "14px", borderRadius: 12, border: "none",
            background: (step?.type === "INTERACT" && !interactionDone) ? "rgba(255,255,255,0.05)" : colour,
            color: (step?.type === "INTERACT" && !interactionDone) ? "rgba(255,255,255,0.2)" : "#fff",
            fontSize: "0.92rem", fontWeight: 700,
            cursor: (step?.type === "INTERACT" && !interactionDone) ? "not-allowed" : "pointer",
          }}
        >
          {isLast ? "Complete ✓" : step?.type === "SUCCESS" ? "Finish →" : "Next →"}
        </button>
      </div>
    </div>
  );
}